### ISSUE TITLE
Enable Packit support for the repository

### ISSUE THREAD

**Issue by gridhead** [fedora-infra/pagure-exporter#109]
We would LOVE to have automated updates pushed to the official Fedora Linux repositories as soon as a new update is made in GitHub.

**Comment by shubhamkarande13** [comment]
Hi @gridhead! I am Shubham, an Outreachy applicant, and I would like to work on this issue!

**Comment by gridhead** [comment]
@shubhamkarande13 this issue is yours to fix :)

**Comment by shubhamkarande13** [comment]
Thank you @gridhead! 
I am following this guide to set up Packit on the repo. I hope I am on the right track.
https://packit.dev/docs/guide#1-set-up-packit-integration

**Comment by gridhead** [comment]
@shubhamkarande13 yep, you are.
