### ISSUE TITLE
Document the newly added `--series` option

### ISSUE THREAD

**Issue by gridhead** [fedora-infra/pagure-exporter#121]
Document the newly added `--series` option

You can find the information here https://github.com/fedora-infra/pagure-exporter/pull/112.

**Comment by anshikavashistha** [comment]
I want to work on this issue

**Comment by gridhead** [comment]
@anshikavashistha I have assigned this issue to you.

**Comment by anshikavashistha** [comment]
Currently I am working on an issue which is not beginner friendly but it need some prerequisite task along with that I want to work on this issue
Thank you @gridhead

**Comment by Munaelekwa** [comment]
Can I work on this issue alongside @anshikavashistha ?

**Comment by gridhead** [comment]
@Munaelekwa I have assigned this issue to you as well.

@anshikavashistha and @Munaelekwa happy collaborating!

**Comment by anshikavashistha** [comment]
Yeah sure @Munaelekwa I would love to collab

**Comment by anshikavashistha** [comment]
@gridhead Where we exactly have to document the -- series option?
I am little bit confused.

**Comment by anshikavashistha** [comment]
I might think we could document --series option [here](https://github.com/fedora-infra/pagure-exporter/blob/main/test/test_main.py)

**Comment by gridhead** [comment]
Fixed via #127 

Closing
