### ISSUE TITLE
429 when transferring bigger repositories

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/pagure-exporter#33]
When trying to migrate bigger repositories (I tested https://pagure.io/fedora-infrastructure) the migration fails with `429 Too many requests`.

The possible solution to this would be to wait for some time when this happens and continue with migration after that.

**Comment by gridhead** [comment]
@Zlopez, thanks for reporting the issue.

This is a known problem and more information about it can be found [here](https://github.com/gridhead/protop2g/pull/32#issuecomment-1761309359).
