### ISSUE TITLE
Use the same issue numbers from Pagure as the same issue number in GitLab

### ISSUE THREAD

**Issue by jwflory** [fedora-infra/pagure-exporter#96]
# Summary

When importing tickets from Pagure, the issue numbers from Pagure should be the same in GitLab.

# Background

Several teams rely on the issue numbers to track key decisions made in the project. Comments in issues will often refer to other issues by number. When migrating from Pagure to GitLab, it is disorienting when the issue numbers do not match and it makes it hard to preserve history. For example, take this example of an issue comment:

**Issue #XY**:
> In ticket #ZY, we agreed to implement the decision after reviewing key feedback from the very important people.

In this case, the "ZY" in Pagure refers to the right issue but the number in GitLab does not.

# Details

This needs some thought due to the fact that Pagure also uses the same sequential order for issues _and_ Pull Requests. If numbers can be skipped, or if a PR can be imported as an issue without the code changes, that could be an option.

# Outcome

Better experience for people moving from Pagure to GitLab, so that critical context is preserved across platforms.

**Comment by gridhead** [comment]
@jwflory, thanks for opening this issue.

As Pagure follows a numbering much akin to that of GitHub, the numbering scheme is shared between pull requests and issue tickets. As a result, your request cannot be fulfilled unless we explicitly cause holes between the numbers assigned to issue tickets to account for the numbers taken up by the pull requests made in the source namespace. I am not sure if that is possible or if that would lead to a long transfer breaking in between.

**Comment by abompard** [comment]
Another way would be to change the content of the issues & comments to replace old numbers with new numbers at import time.

**Comment by jwflory** [comment]
@gridhead I wonder how difficult it is to pull the text of Pagure Pull Requests into GitLab issues, since the comments remain the same. The git diffs would be lost, but the discussion and comments in Pagure Pull Requests would still be useful as GitLab issues, especially if it means preserving the original order of Pagure into GitLab.

@abompard I think this is what the tool already does with the title of the imported issues, but my use case was more for comments that reference other issues in the same repository. E.g. In Issue 5, I write a comment `We decided in ticket #2 to implement XYZ decision`. I would like that reference to be preserved in migration.

**Comment by gridhead** [comment]
I think I might have a piece of good news for you folks.

While banging my head on #60, I revisited the GitLab API for manually creating issue tickets. I passed the `iid` value in using a token that administrator rights on the destination namespace and the following is what happened. I can add custom IDs to the issue tickets that are being created at the destination namespace at the expense of introducing holes in the numbering if the said index has been used for identifying a pull request in the source namespace.

![image](https://github.com/fedora-infra/pagure-exporter/assets/49605954/ef89a9bc-593a-4613-9c0a-4a643652a31b)

Please note that while this might fix the inter-referencing of issue tickets and comments that go like this `This has been referenced in #2`, this does not fix that of those that go like this `This has been referenced [here](https://pagure.io/some-project/project-name/issues/2)`. Those would still require some wrangling with regular expressions to change the contents of the issue ticket and comments and that could be another issue ticket.

Is this something that we are okay with?

**Comment by gridhead** [comment]
A note for myself.

I went ahead and tried to create an issue ticket with a custom ID after an issue ticket was already created on the same ID to see if the `python-gitlab` module could overwrite it but alas, that is not the case.

```
>>> from requests import Session
>>> sess = Session()
>>> from gitlab import Gitlab as gtlb
>>> gtlbobjc = gtlb(url="https://gitlab.com", session=sess, private_token="ADD_TOKEN_HERE")
>>> a = gtlbobjc.projects.get(id="42823949")
>>> a.issues.create({"iid":"7000", "title":"7000 test with python-gitlab", "description":"7000 test with python-gitlab"})
<ProjectIssue iid:7000 title:7000 test with python-gitlab>
>>> a.issues.create({"iid":"7000", "title":"7000 test repeat with python-gitlab", "description":"7000 test repeat with python-gitlab"})
Traceback (most recent call last):
  File "/home/t0xic0der/Projects/paguregitlab/venv/lib/python3.11/site-packages/gitlab/exceptions.py", line 340, in wrapped_f
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/t0xic0der/Projects/paguregitlab/venv/lib/python3.11/site-packages/gitlab/mixins.py", line 301, in create
    server_data = self.gitlab.http_post(path, post_data=data, files=files, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/t0xic0der/Projects/paguregitlab/venv/lib/python3.11/site-packages/gitlab/client.py", line 1001, in http_post
    result = self.http_request(
             ^^^^^^^^^^^^^^^^^^
  File "/home/t0xic0der/Projects/paguregitlab/venv/lib/python3.11/site-packages/gitlab/client.py", line 794, in http_request
    raise gitlab.exceptions.GitlabHttpError(
gitlab.exceptions.GitlabHttpError: 409: Duplicated issue

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/t0xic0der/Projects/paguregitlab/venv/lib/python3.11/site-packages/gitlab/exceptions.py", line 342, in wrapped_f
    raise error(e.error_message, e.response_code, e.response_body) from e
gitlab.exceptions.GitlabCreateError: 409: Duplicated issue
```

**Comment by jwflory** [comment]
> _**@gridhead wrote…**_
> Please note that while this might fix the inter-referencing of issue tickets and comments that go like this This has been referenced in #2, this does not fix that of those that go like this This has been referenced [here](https://pagure.io/some-project/project-name/issues/2). Those would still require some wrangling with regular expressions to change the contents of the issue ticket and comments and that could be another issue ticket.

It is acceptable that those comments which have hard-coded Markdown to a Pagure URL will remain that way in GitLab. I am only looking for relative references (e.g. someone writing "`#2`" in an issue) to continue working.
