### ISSUE TITLE
Change the documentation to use `venv` instead of `virtualenv`

### ISSUE THREAD

**Issue by gridhead** [fedora-infra/pagure-exporter#99]
On investigating the differences between the two, it was found that the either of two can be used for the same purpose as the project ties to attain and hence, the preference would be towards the one that is made available out of the box.

**Comment by feizai2003** [comment]
I'm interested in this and attempt to resolve this issue

**Comment by gridhead** [comment]
@feizai2003, thanks! I have assigned this issue to you.
